use_frameworks!

target 'IGListKitExamples' do
  pod 'IGListKit', :path => '../../IGListKit.podspec'
  pod 'SwiftLint'
end

target 'IGListKitMessageExample' do
  pod 'IGListKit', :path => '../../IGListKit.podspec'
end

target 'IGListKitTodayExample' do
  pod 'IGListKit', :path => '../../IGListKit.podspec'
end
