use_frameworks!
platform :ios, '9.0'

target 'IGListKitExamples' do
  pod 'IGListDiffKit', :path => '../../IGListDiffKit.podspec'
  pod 'IGListKit', :path => '../../IGListKit.podspec'
end

target 'IGListKitMessageExample' do
  pod 'IGListDiffKit', :path => '../../IGListDiffKit.podspec'
  pod 'IGListKit', :path => '../../IGListKit.podspec'
end

target 'IGListKitTodayExample' do
  pod 'IGListDiffKit', :path => '../../IGListDiffKit.podspec'
  pod 'IGListKit', :path => '../../IGListKit.podspec'
end
