# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

target 'ModelingAndBinding' do
  pod 'IGListKit', :path => '../../IGListKit.podspec'
  pod 'SDWebImage', '~> 4.0.0'
end
