# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!

pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
pod 'SDWebImage'

target 'ModelingAndBinding' do
end

