opt_in_rules: # some rules are only opt-in
  - empty_count
disabled_rules:
  - force_unwrapping
  - comma
  - line_length
included:
  - IGListKitExamples
  - IGListKitMessageExample
  - IGListKitTodayExample
excluded:
  - Pods
force_cast: warning
force_try: warning
weak_delegate: error
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - pk
    - day
    - map
    - row
    - nib
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
